### ISSUE TITLE
Cannot read property 'route' of undefined

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#1267]
Server logs:

```
TypeError: Cannot read property 'route' of undefined
    at Route.computeMatch (/home/ubuntu/plant/node_modules/react-router/Route.js:68:22)
    at new Route (/home/ubuntu/plant/node_modules/react-router/Route.js:47:20)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/home/ubuntu/plant/node_modules/react-dom/lib/ReactCompositeComponent.js:297:16)
    at ReactCompositeComponentWrapper._constructComponent (/home/ubuntu/plant/node_modules/react-dom/lib/ReactCompositeComponent.js:284:19)
    at ReactCompositeComponentWrapper.mountComponent (/home/ubuntu/plant/node_modules/react-dom/lib/ReactCompositeComponent.js:187:21)
    at Object.mountComponent (/home/ubuntu/plant/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/ubuntu/plant/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/ubuntu/plant/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/home/ubuntu/plant/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/ubuntu/plant/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
/home/ubuntu/plant/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^
```

**Comment by guyellis** [comment]
Caused by doing server side rendering but not including the react-router-server for that.
