### ISSUE TITLE
OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#1283]
Turns out this error was a red-herring.
```
/home/ubuntu/plant/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy 
          (/home/ubuntu/plant/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy
           (/home/ubuntu/plant/node_modules/passport-facebook/lib/strategy.js:54:18)
    at Object.fbPassport (/home/ubuntu/plant/lib/config/passport-facebook.js:9:16)
    at module.exports (/home/ubuntu/plant/lib/server.js:43:16)
    at Object.<anonymous> (/home/ubuntu/plant/server.js:5:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

```

**Comment by guyellis** [comment]
nginx logs have the clue as to what's happening:

```
2017/09/05 02:15:20 [error] 831#831: 
*16576 upstream sent too big header while reading response header from upstream,
 client: <ip-redacted>, server: plaaant.com,
 request: "GET /auth/google/callback?code=<redacted> HTTP/1.1",
 upstream: "http://<host-ip-redacted>/auth/google/callback?code=<redacted>",
 host: "plaaant.com",
 referrer: "https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=<redacted>"
```

**Comment by guyellis** [comment]
Closing - this is a server nginx problem.
