### ISSUE TITLE
Travis test fail timeouts

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#3073]
Tests on Travis have been failing with fairly high frequency on first run and then passing on a subsequent run. Seems to be from timeouts. Use this ticket to track where this is happening to see if we can identify a particular test.

```shell
Summary of all failing tests
FAIL test/app/actions/actions.test.ts
  ● Test suite failed to run
    Timeout - Async callback was not invoked within the 60000ms timeout specified by
 jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms
 timeout specified by jest.setTimeout.
      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
Test Suites: 1 failed, 1 skipped, 38 passed, 39 of 40 total
Tests:       1 skipped, 231 passed, 232 total
Snapshots:   76 passed, 76 total
Time:        101.087s
```

**Comment by guyellis** [comment]
Same test on next failure:

```shell
FAIL test/app/actions/actions.test.ts
  ● Test suite failed to run
    Timeout - Async callback was not invoked within the 60000ms timeout specified by
 jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms
 timeout specified by jest.setTimeout.
      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
          at runMicrotasks (<anonymous>)
Test Suites: 1 failed, 1 skipped, 38 passed, 39 of 40 total
Tests:       1 skipped, 231 passed, 232 total
Snapshots:   76 passed, 76 total
Time:        99.142s
```

**Comment by guyellis** [comment]
Today on a local pre-commit hook:

```shell
[4]  FAIL  test/app/components/plant/PlantEdit.test.tsx
  ● Test suite failed to run
[4] 
[4]     Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.
[4] 
      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
```

**Comment by guyellis** [comment]
Today on Travis

```shell
Summary of all failing tests
FAIL test/app/actions/actions.test.ts
  ● Test suite failed to run
    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.
      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
          at runMicrotasks (<anonymous>)
FAIL test/lib/db/mongo/update.test.ts
  ● Test suite failed to run
    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.
      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
```

**Comment by guyellis** [comment]
Haven't seen this for a long time - closing.
