### ISSUE TITLE
Error in SSR

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#3210]
Error seems to be related to a link posted in FB but I think that's a red herring.

Somehow the `.woff` font is being past in as the plantId.

```
level:error
module:express-request
moduleName:lib/render/plant
msg:Unexpected error in SSR of Plant

shortStack:
[0]:    at MongoDb.getNotesByPlantId (/home/ubuntu/plant/lib/db/mongo/index.ts:894:31)
[1]:    at getNotes (/home/ubuntu/plant/lib/db/single-plant.ts:10:35)
[2]:    at Object.exports.singlePlant (/home/ubuntu/plant/lib/db/single-plant.ts:49:5)
[3]:    at exports.renderPlant (/home/ubuntu/plant/lib/render/plant.ts:32:32)
```

**Comment by guyellis** [comment]
Fairly certain this is fixed now.
