### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#399]
Travis builds are failing although local builds are not. Stack:

```
    at Object.createErr [as create] (/home/travis/build/guyellis/plant/node_modules/errs/lib/errs.js:97:11)
    at Request._callback (/home/travis/build/guyellis/plant/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/home/travis/build/guyellis/plant/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/travis/build/guyellis/plant/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/travis/build/guyellis/plant/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'Error',
  error: 'badmatch',
  reason: '{ok,[{ok,{doc,<<"_design/plants">>
```

**Comment by guyellis** [comment]
The major build break happened from Travis builds 1001 to 1002. Change from 1001 to 1002 was SinonJS from 1.17.4 to 1.17.5.

**Comment by guyellis** [comment]
Closing this because Travis is green now although the solution of switching from Cloudant to Travis' CouchDB is not optimal.
